## Introduction to tensors

In [1]:
#Import Tensorflow
import tensorflow as tf

In [2]:
##Create a scalar (rank  0 tensor)

scalar= tf.constant(7)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
## Check the number of dimensions of a tensor. (ndim for boyut için)
scalar.ndim


print("Scalar 0 boyutluymuş")
scalar.ndim


Scalar 0 boyutluymuş


0

In [7]:
## Vektör oluşturma (0 dan dahafazla boyutu olan tensör)

vector = tf.constant([10,10])


In [8]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [9]:
vector.ndim

1

In [11]:
## Matris oluşturma (1 boyuttan daha fazla)

matrix = tf.constant([[10,7],
                    [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [12]:
matrix.ndim

2

## Tensör Oluşturma
Normalde tensörler otomatik oluşturulur. Çok nadir olmak üzere tensörler, özellikle data ile çalışırken, tensör oluşturulabilir.

In [13]:
## tf.Variable ile tf.constant arasındaki fark, tf.constant immutable yani değiştirlemez, ancak tf.Variable daha sonra değiştirlebilir.(mutable)

In [17]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10.7]),
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([10.7], dtype=float32)>,))

In [20]:
# Will error (requires the .assign() method)
changable_tensor[0] = 7
changable_tensor
     

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:

# Won't error
changable_tensor[0].assign(7)
changable_tensor
     

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [22]:

# Will error (can't change tf.constant())
unchangeable_tensor[0].assign(7)
unchangleable_tensor

NameError: name 'unchangeable_tensor' is not defined

## Rastgele tensor oluşturma

In [23]:
## Bir sinir ağı, rastgele patternler ile öğrenmeye başlar.

In [24]:
# Randım tensor oluştumak istersebiz, tf.random.Generator() kodunu kullanmanız gerekir.

In [25]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

# seed (tohum) bir rastgele sayı üreteci (random number generator) için başlangıç noktasını belirlemek için kullanılan bir değerdir. 
#Rastgele sayı üreteçleri, aslında deterministik olmayan, yani tekrarlandığında aynı sonuçları vermeyen matematiksel algoritmalar kullanırlar. Ancak, bu algoritmaların başlangıç noktasını belirlemek için kullanılan bir tohum (seed) değeri verildiğinde, aynı tohum değerini kullanarak aynı sıradaki rastgele sayıları üretebilirsiniz.

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [26]:

# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [27]:

# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)
     

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

TensorFlow'da tf.random.shuffle işlevi, bir tensörün içindeki öğelerin sırasını rastgele bir şekilde değiştirmek için kullanılır. Örneğin, yukarıdaki kod örneğinde not_shuffled adlı bir tensör tanımlanmış ve sonra bu tensör tf.random.shuffle kullanılarak karıştırılmıştır. Bu işlem sonucunda, not_shuffled tensöründeki öğelerin sırası rastgele bir şekilde değiştirilmiş olur.

In [28]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)
## seedi aynı girsen bile aynı sonucu vermmmmmeeeezzz.
##çünkü operasyon düzeyinde 42 ayarladık ondan farklı sonuçlar üretir.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

TensorFlow'da rastgele sayı üreteci (random number generator) kullanılırken, iki seviyede tohum (seed) ayarlanabilir: global seviye tohumu (global seed) ve işlem seviye tohumu (operation seed). Bu tohumlar, rastgele sayıların nasıl üretildiğini kontrol etmek için kullanılır.

Rule #4, bu iki tohumun birlikte kullanıldığını belirtir. Yani, rastgele sayı üretme işlemi sırasında hem global seviye tohumu hem de işlem seviye tohumu dikkate alınır. İşte bu iki tohumun nasıl çalıştığına dair bir açıklama:

Global Seviye Tohumu (Global Seed): tf.random.set_seed() gibi bir işlemle belirlenen global seviye tohum, TensorFlow'un rastgele sayı üreteci için bir başlangıç noktasıdır. Bu tohum, TensorFlow oturumu başladığında veya kod her çalıştığında aynı olacak şekilde ayarlanabilir. Bu, tekrarlanabilir sonuçlar elde etmek için kullanışlıdır.

İşlem Seviye Tohumu (Operation Seed): Bir rastgele sayı üreteci işlemi gerçekleştirilirken, bu işlem için özel bir işlem seviye tohumu ayarlanabilir. Örneğin, tf.random.shuffle(seed=42) gibi bir işlemde, işlem seviye tohumu belirtilmiştir. Bu tohum, yalnızca belirli bir işlemde kullanılacak ve bu işlemdeki rastgele sayı üretimini etkileyecektir.

Sonuç olarak, rastgele sayı üreteci, global seviye tohum ve işlem seviye tohumunu birlikte kullanarak rastgele sayıları üretir. Bu, aynı tohumlarla başladığınızda her seferinde aynı rastgele sıralamayı veya sonuçları elde etmenizi sağlar. Bu, model eğitimi sırasında veya denemelerde tekrarlanabilir sonuçlar elde etmek istediğinizde özellikle önemlidir.

In [29]:

# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)
## işte şimdi globali çektik ondan aynıyı aldık.    

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [30]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

## Tensor yapmak için diğer yollar

In [31]:

# Bütün değerleri bir olan tensor 
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [32]:
# Bütün değerleri sıfır olan tensor 
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

## Numpy ile tensör
Tensörlerini numpy arraylere çevirebilirsin.
Farkı şudur, tensörler GPUda çalışabilirken, NumPy arrayler sadece CPUda çalışır

# Not
Bir matris veya tensor büyük harflerle değişkenleri isimlendirilirken, vektörler küçük harfle isimlendirilir.

In [33]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # 1 ile 25 değerleri arasında sayı değerleri olan bir numoy dizisi oluştur.
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # 2*4*3 elementli bir matris oluşturuyoruz.
numpy_A, A
     

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

# Tensörlerden Bilgi Alma

Tensör terimleri;

Shape: Tensörlerin her bir boyutunun uzunluğunu ifade eder.
Rank: Tensörlerin boyut sayısı.
Axis veya Dimension: Tensörlerin belirli bir boyutu.
Size: Tensörlerde bulunan toplam öge sayısı.

In [34]:
# Rank 4 tensör oluşturma (4 boyutlu)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor
     

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)


(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [36]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [37]:

# Her bir boyutun ilk iki ögesini alma.
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [38]:

# Son boyut hariç, bütün boyutların ilk itemini alma
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:

# Rank 2 tensör oluşturma.
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Son ögelerini alma her bir satırın.
rank_2_tensor[:, -1]
     

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [40]:
# Fazladan boyut ekleme. (En son satıra)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # Python'da "..." "önceki tüm boyutlar" anlamına gelir
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>)

In [41]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" son satır anlamına gelir.


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

# Tensörleri manipüle etme (Tensör operasyonları)

Tensorlerin desenlerini bulmak onlar üzerinde operasyon yapmayı gerektirir.
Tensorflowda model yaparken tensorflow bunu senin için otomatik yapar.

# Temel operasyonlar
, -, * gibi Pyhton operatörlerini kullanarak temel matematik işlemlerinin çoğunu doğrudan tensörler üzerinde gerçekleştirebilirsiniz.

In [42]:
# Toplama operatörünü kullanarak tensöre değerler ekleyebilirsiniz

tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [43]:
## orijinal tensör değişmez!
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [44]:
##Çarpma (öge bazında)
tensor * 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [45]:
#Çıkarma
tensor - 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [46]:
# '*' (çarpma) operatörünün tensorflow fonksiyonu eşdeğerini kullanın

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [48]:
## Bu işlemlerden sonra, orijinal tensör değişmez, değiştirmek için değişken eşitlemelisin.
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

## Matris çarpımı

In [49]:
## tf.matmul operasyonu ile yapılır.

In [50]:

# TensorFlow'da matris çarpımı
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [51]:

# Python operatörü '@' ile matris çarpımı
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [52]:
# (3, 2) tensor oluşturma
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Başka bir (3, 2) tensör oluşturma

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [53]:
# Bunları matrisle çarpmaya çalışırsanız hata alırsınız.

X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [54]:
# (3, 2) -> (2, 3) şekline reshapeliyoruz.;
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [55]:
## Şimdi çarpabilirsin
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [56]:
## Transpoz alma
tf.transpose(X)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [57]:
## Matris çarpımı
tf.matmul(tf.transpose(X), Y)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [58]:
# Parametre ayarlayarak da halledebilirsin
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False) ## Transpoz alınıp çarpıldı ondan boyut çarğıma elverişli oldu, çarpım gerçekleşti.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

## Dot product

In [59]:
#X ve Y üzerinde nokta çarpımını gerçekleştirilmesi (X'in transpoze edilmesini gerektirir)

tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [60]:
# X ve Y arasında matris çarpımı gerçekleştirin ( Y reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [61]:
# Y'nin şekillerini kontrolü , Y'yi yeniden şekillendirilmesi ve Y'yi değiştirilmesi.
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape
     

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [62]:
# Y'nin değer kontrolü , reshape Y and Y tranpozu
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))
     

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


# Bir tensörün veri tipinin değiştirilmesi.

Bazen tensörünüzün varsayılan veri tipini değiştirmek isteyebilirsiniz. Daha az hassasiyet kullanarak hesaplama yapmak istediğinizde bu durum yaygındır (örneğin, 16 bitlik kayan noktalı sayılara karşı 32 bitlik kayan noktalı sayılar). Daha az hassasiyetle hesaplama, mobil cihazlar gibi daha az bilgi işlem kapasitesine sahip cihazlarda faydalıdır (çünkü daha az bit, hesaplamalar için daha az alan gerektirir).

In [63]:
# Float32 default olarak gelen veri tipine sahip tensör oluşturma.
B = tf.constant([1.7, 7.4])

# Int32 default olarak gelen veri tipine sahip tensör oluşturma.
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>)

In [64]:
# float32den float16ya değiştirme.(Hassasiyet azalır)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [65]:
# int32den float32ye çevirme.
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

## Mutlak değer alma

In [66]:
# Negatif değere sahip tensor oluşturma.
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [67]:
#Mutlak değer alma işlemi
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

## Min ,max, ortalama, toplam değerler bulma

In [68]:
# Değerleri 0 ile 100 arasında olan, 50 adet rastgele değere sahip tensor oluşturma.

E= tf.constant(np.random.randint(low=0, high = 100, size = 50))

E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([56, 10, 10, 81, 94, 70, 40, 99, 20, 20, 68, 76, 44, 51, 50,  4, 12,
       63, 11, 90, 67, 87, 34, 99, 28, 33, 60, 45, 36, 14,  8,  9, 65, 17,
       92, 59, 74, 66, 84, 20, 75, 41, 56,  8, 13, 38, 29, 18, 61, 10])>

In [69]:
# Minimumu bulma
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [72]:
#Maximumu bulma

tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [73]:
# Ortalama bulma

tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [74]:
#Toplamı bulma

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2315>

## Pozisyonel maksimum ve minimumu bulma

In [75]:
# 50 adet ögeye sahip ve sadece 0 ve 1 arasında değerlerden oluşan, tensor oluşturma.

F= tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.28598444, 0.3941755 , 0.37281904, 0.23276312, 0.43823463,
       0.41912273, 0.76644813, 0.59124677, 0.80911411, 0.26922625,
       0.23502863, 0.80312459, 0.37777686, 0.46409146, 0.99530768,
       0.45369203, 0.56829095, 0.61369409, 0.46513597, 0.10029234,
       0.56042819, 0.51558947, 0.68312891, 0.90574984, 0.20275261,
       0.6123088 , 0.35429572, 0.56139598, 0.6328589 , 0.01971305,
       0.5088851 , 0.68002922, 0.490582  , 0.62751393, 0.38430484,
       0.99722148, 0.78406979, 0.22813983, 0.69694262, 0.93886138,
       0.2947295 , 0.87974819, 0.73598592, 0.69325965, 0.04309447,
       0.09939657, 0.79346181, 0.8871729 , 0.27553491, 0.10918057])>

In [76]:
## Maksimum ögenin yerini bulma (pozisyonunu bulma)

tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [77]:
# Minimum olan ögenin yerini bulma (pozisyonunu bulma)
tf.argmin(F)


<tf.Tensor: shape=(), dtype=int64, numpy=29>

In [78]:
## tf.argsort ise çıktı olarak array verir ve küçükten büyüğe indeksleri verir.

In [79]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 35
The maximum value of F is: 0.9972214781177134
Using tf.argmax() to index F, the maximum value of F is: 0.9972214781177134
Are the two max values the same (they should be)? True


## Bir tensörü sıkıştırma (squeezing) (Bütün tek boyutların kaldırılması)

In [82]:
# 0 ile 100 arasında 50 sayıdan oluşan 5. derece (5 boyut) tensör oluştuulması
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [83]:
# Tensör G'nin squeeze edilmesi. (1 boyutun tamamını kaldırın)

G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

## One-hot encoding

In [84]:
# List oluşturma
some_list = [0, 1, 2, 3]

# One hot encode işlemi
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [85]:
# on ve off encoding  için değer özelleştirlmesi.

tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")
     

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

Varsayılan 0 ve 1 yerine on_value ve off_value için de değerler belirleyebilirsiniz.

## Kare, logaritma ve karekök alma

In [86]:
# Tensor oluşturma
H = tf.constant(np.arange(1, 10))
H
     

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [87]:

# Karesi
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [89]:
# Karekök alma, hata alacağız. çünkü integer olmamalı.
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [90]:

# H değişkenini float32ye cast ediyoruz.
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [91]:
# Tekrardan karekök alıyoruz.
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [92]:
# Logaritmasını alıyoruz. Float olmalı!
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# tf.Variable tensorlerini manipüle etme.

In [93]:
## Variable tensör oluştuma.
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [94]:
# Son indeksindeki ögeyi 50ye eşitliyoruz.
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [95]:
# Değişiklik orijinalinde de oldu, son değer artık 4 değil 50.
I
     

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [96]:

# Bütün I değişkeni ögelerine 10 ekliyoruz.
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

In [97]:
# Orjinali de değişti.
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

# Tensörler ve NumPy

In [98]:
## NumPy dizisinden tensör oluşturma.
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [99]:
# np.array() ile tensör J'yi NumPy'ye dönüşümü.
np.array(J), type(np.array(J))


(array([ 3.,  7., 10.]), numpy.ndarray)

In [101]:
# Tensör J'yi .numpy() ile NumPy'ye dönüşümü.
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [102]:
# NumPy'den ve bir diziden tensör oluşturma
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype
     

(tf.float64, tf.float32)

# @tf.function kullanımı

In [104]:
# Basit bir fonksiyon oluşturma.
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)
     

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [105]:

# Aynı işlevi oluşturun ve tf.function ile dekore edilmesi.
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)
     

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

Yukarıdaki iki işlev arasında (dekore edilmiş olan ve dekore edilmemiş olan) hiçbir fark görmediyseniz haklısınız. Farkın büyük kısmı sahne arkasında yaşanıyor. Bunlardan en önemlilerinden biri, mümkün olan yerlerde potansiyel kod hızlandırmalarıdır.

# GPUlara erişim.

In [106]:
print(tf.config.list_physical_devices('GPU'))


[]
